nelmio_api_doc:
    documentation:
        info:
            title: Subscription Management App
            description: 'iOS or Google mobile apps can use this API for in-app purchases, authentication, and subscription management.'
            version: 1.0.0

        components:
            securitySchemes:
                ClientToken:
                    type: apiKey
                    in: header
                    name: client-token
                    description: "Client token for authentication."


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
